version: "3.7"
services:
  #PHP
  app:
    build:
      args:
        user: root-rtik
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: img-rtik-homepage/php
    container_name: ct-rtik
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - network-rtik
  nginx:
    image: nginx:alpine
    container_name: ct-nginx-rtik
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - network-rtik
networks:
  network-rtik:
    driver: bridge
